# Generated by Django 3.2.13 on 2022-04-30 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyClass',
            fields=[
                ('class_id', models.IntegerField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=20)),
                ('class_dailyrate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('class_over_m_fee', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'lxy_class',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyCustomer',
            fields=[
                ('cust_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('cust_street', models.CharField(max_length=30)),
                ('cust_city', models.CharField(max_length=20)),
                ('cust_state', models.CharField(max_length=20)),
                ('cust_zip', models.IntegerField()),
                ('cust_email', models.CharField(max_length=30)),
                ('cust_phone', models.BigIntegerField()),
                ('cust_type', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'lxy_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyDiscount',
            fields=[
                ('disc_numb', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('disc_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('disc_type', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'lxy_discount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyInvoice',
            fields=[
                ('invo_numb', models.BigIntegerField(primary_key=True, serialize=False)),
                ('invo_date', models.DateTimeField()),
                ('invo_amou', models.DecimalField(decimal_places=2, max_digits=7)),
                ('invo_payed', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'lxy_invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyOffice',
            fields=[
                ('offi_id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('offi_street', models.CharField(max_length=50)),
                ('offi_city', models.CharField(max_length=20)),
                ('offi_state', models.CharField(max_length=20)),
                ('offi_zip', models.IntegerField()),
                ('offi_phone', models.BigIntegerField()),
            ],
            options={
                'db_table': 'lxy_office',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyPayment',
            fields=[
                ('paym_numb', models.BigIntegerField()),
                ('paym_type', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('paym_amou', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paym_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'lxy_payment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyRentServ',
            fields=[
                ('serv_numb', models.BigIntegerField(primary_key=True, serialize=False)),
                ('pick_date', models.DateTimeField()),
                ('drop_date', models.DateTimeField()),
                ('sodom', models.IntegerField()),
                ('eodom', models.IntegerField()),
                ('dail_limi', models.SmallIntegerField()),
                ('unlimi', models.CharField(max_length=2000)),
            ],
            options={
                'db_table': 'lxy_rent_serv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyVehicle',
            fields=[
                ('vehi_lice', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('vehi_vin', models.CharField(max_length=17)),
                ('vehi_make', models.CharField(max_length=20)),
                ('vehi_model', models.CharField(max_length=20)),
                ('vehi_year', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'lxy_vehicle',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyCredit',
            fields=[
                ('paym_type', models.OneToOneField(db_column='paym_type', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cars.lxypayment')),
                ('cred_numb', models.BigIntegerField()),
            ],
            options={
                'db_table': 'lxy_credit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyCustCorp',
            fields=[
                ('cust', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cars.lxycustomer')),
                ('corp_reginum', models.CharField(max_length=20)),
                ('corp_eid', models.CharField(max_length=20)),
                ('corp_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lxy_cust_corp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyCustIndi',
            fields=[
                ('cust', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cars.lxycustomer')),
                ('indi_dln', models.CharField(max_length=13, unique=True)),
                ('indi_fname', models.CharField(max_length=20)),
                ('indi_mname', models.CharField(blank=True, max_length=20, null=True)),
                ('indi_lname', models.CharField(max_length=20)),
                ('indi_icn', models.CharField(max_length=50)),
                ('indi_ipn', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lxy_cust_indi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyDebit',
            fields=[
                ('paym_type', models.OneToOneField(db_column='paym_type', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cars.lxypayment')),
                ('debi_numb', models.BigIntegerField()),
            ],
            options={
                'db_table': 'lxy_debit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyDiscCorp',
            fields=[
                ('disc_numb', models.OneToOneField(db_column='disc_numb', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cars.lxydiscount')),
                ('disc_corp_sdate', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lxy_disc_corp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyDiscIndi',
            fields=[
                ('disc_numb', models.OneToOneField(db_column='disc_numb', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cars.lxydiscount')),
                ('disc_indi_sdate', models.DateTimeField()),
                ('disc_indi_edate', models.DateTimeField()),
            ],
            options={
                'db_table': 'lxy_disc_indi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LxyGift',
            fields=[
                ('paym_type', models.OneToOneField(db_column='paym_type', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='cars.lxypayment')),
                ('gift_numb', models.BigIntegerField()),
            ],
            options={
                'db_table': 'lxy_gift',
                'managed': False,
            },
        ),
    ]
