# Generated by Django 3.2.13 on 2022-05-02 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_platformadmin_platformuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlatformAdmin',
            new_name='LxyAdmin',
        ),
        migrations.RenameModel(
            old_name='PlatformUser',
            new_name='LxyUser',
        ),
    ]
