# Generated by Django 3.2.13 on 2022-05-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20220501_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lxydiscindi',
            name='disc_numb',
        ),
        migrations.DeleteModel(
            name='LxyDiscCorp',
        ),
        migrations.DeleteModel(
            name='LxyDiscIndi',
        ),
        migrations.DeleteModel(
            name='LxyDiscount',
        ),
    ]
