# Generated by Django 3.2.13 on 2022-05-10 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20220509_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lxycredit',
            name='paym_type',
        ),
        migrations.RemoveField(
            model_name='lxydebit',
            name='paym_type',
        ),
        migrations.RemoveField(
            model_name='lxygift',
            name='paym_type',
        ),
        migrations.DeleteModel(
            name='LxyInvoice',
        ),
        migrations.DeleteModel(
            name='LxyCredit',
        ),
        migrations.DeleteModel(
            name='LxyDebit',
        ),
        migrations.DeleteModel(
            name='LxyGift',
        ),
        migrations.DeleteModel(
            name='LxyPayment',
        ),
    ]
